#!/usr/bin/env bash
#
# Description:
#   download and prepare heidisql for snap
#
# Date: Mar 09 2020
#

dlf2k () {
    ver=$(wget https://api.github.com/repos/HeidiSQL/HeidiSQL/releases -qO - 2>&1 | grep tag_name | cut -d'"' -f4 | sed s'/v//' | head -n1)
    wget https://www.heidisql.com/downloads/releases/HeidiSQL_${ver}_64_Portable.zip &> /dev/null
}

dli7z16x64 () {
    for dldebs in https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip_16.02+dfsg-4_amd64.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip-full_16.02+dfsg-4_amd64.deb 
    do
    wget $dldebs &> /dev/null
    done

    for pkgdebins in p7zip_16.02+dfsg-4_amd64.deb p7zip-full_16.02+dfsg-4_amd64.deb
    do
    sudo apt install ./$pkgdebins -y &> /dev/null
    rm $pkgdebins
    done
}

mkf2k () {
    mkdir -p ./{wine-runtime,wine-platform,bin} && mkdir -p sommelier/hooks && mkdir -p usr/share/{pixmaps,applications}
    7z x "HeidiSQL_${ver}_64_Portable.zip" -o"usr/share/heidisql-wine" &> /dev/null
    cp usr/share/heidisql-wine/heidisql.exe usr/share/heidisql-wine/heidisql-wine.exe
    find "usr" -type d -execdir chmod 755 {} +
}

mkdsk () {
ver=$(wget https://api.github.com/repos/HeidiSQL/HeidiSQL/releases -qO - 2>&1 | grep tag_name | cut -d'"' -f4 | sed s'/v//' | head -n1)
cat > heidisql-wine.desktop <<'EOF1'
[Desktop Entry]
Name=HeidiSQL
GenericName=HeidiSQL
Comment=HeidiSQL snap version
Encoding=UTF-8
Version=
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/heidisql-wine.png
TryExec=heidisql-wine
Exec=heidisql-wine %F
StartupWMClass=heidisql.exe
Categories=Development,
MimeType=text/plain;
EOF1
sed -i -e 's|Version=|Version='"$ver"'|g' heidisql-wine.desktop
}

dlf2k
dli7z16x64
mkdsk
mkf2k
mv pre-install sommelier/hooks && mv heidisql-wine.desktop usr/share/applications && mv heidisql-wine.png usr/share/pixmaps && cp -R -p {sommelier,bin,usr,wine-runtime,wine-platform} $SNAPCRAFT_PART_INSTALL