#!/usr/bin/env bash
#
# Description:
#   download and prepare heidisql for snap
#
# Date: Mar 09 2020
#

dlf2k () {
    ver=$(wget -qO - https://mobaxterm.mobatek.net/download-home-edition.html | grep -i 'MobaXterm.*Home Edition v' | head -n1 | sed -E 's/.*v([0-9.]+).*/\1/')
    url=$(wget -qO - https://mobaxterm.mobatek.net/download-home-edition.html | grep -i 'https://download.mobatek.net.*portable.*.zip' | head -n1 | sed -nE 's/.*(https:\/\/download\.mobatek\.net[^"]*\.zip).*/\1/p' | head -n1)
    wget ${url} &> /dev/null
}

dli7z16x64 () {
    for dldebs in https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip_16.02+dfsg-4_amd64.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip-full_16.02+dfsg-4_amd64.deb 
    do
    wget $dldebs &> /dev/null
    done

    for pkgdebins in p7zip_16.02+dfsg-4_amd64.deb p7zip-full_16.02+dfsg-4_amd64.deb
    do
    sudo apt install ./$pkgdebins -y &> /dev/null
    rm $pkgdebins
    done
}

mkf2k () {
    mkdir -p ./{wine-runtime,wine-platform,bin} && mkdir -p sommelier/hooks && mkdir -p usr/share/{pixmaps,applications}
    7z x "MobaXterm_Portable_v${ver}.zip" -o"usr/share/mobaxterm-wine" &> /dev/null
    cp usr/share/mobaxterm-wine/MobaXterm_Personal_${ver}.exe usr/share/mobaxterm-wine/mobaxterm-wine.exe
    find "usr" -type d -execdir chmod 755 {} +
}

mkdsk () {
ver=$(wget -qO - https://mobaxterm.mobatek.net/download-home-edition.html | grep -i 'MobaXterm.*Home Edition v' | head -n1 | sed -E 's/.*v([0-9.]+).*/\1/')
cat > mobaxterm-wine.desktop <<'EOF1'
[Desktop Entry]
Name=MobaXterm
GenericName=MobaXterm
Comment=MobaXterm snap version
Encoding=UTF-8
Version=
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/mobaxterm-wine.png
TryExec=mobaxterm-wine
Exec=mobaxterm-wine %F
StartupWMClass=mobaxterm-wine.exe
Categories=Development,
MimeType=text/plain;
EOF1
sed -i -e 's|Version=|Version='"$ver"'|g' mobaxterm-wine.desktop
}

dlf2k
dli7z16x64
mkdsk
mkf2k
mv pre-install sommelier/hooks && mv mobaxterm-wine.desktop usr/share/applications && mv mobaxterm-wine.png usr/share/pixmaps && cp -R -p {sommelier,bin,usr,wine-runtime,wine-platform} $SNAPCRAFT_PART_INSTALL