name: mobaxterm-wine
title: MobaXterm (Wine)
summary: MobaXterm advanced terminal and SSH client for Windows, via Wine
description: MobaXterm provides an advanced terminal, SSH client, X11 server, and many network tools for Windows. This version uses Wine to run MobaXterm on Linux through Snap.
adopt-info: mobaxterm-wine

confinement: strict
grade: stable
architectures:
  - build-on: amd64
    run-on: [amd64]
base: core18
compression: lzo

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-6-staging:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-6-staging

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml="         # Prevent pop-ups about Wine Mono and Wine Gecko
  WINEARCH: "win64"

apps:
  mobaxterm-wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "$SNAP_USER_DATA/mobaxterm-wine/mobaxterm.exe"
      SOMMELIER_KEEP_CWD: 1  # Don't change the working directory so relative paths still work
    plugs:
      - home
      - network
    desktop: usr/share/applications/mobaxterm-wine.desktop
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network

parts:
  mobaxterm-wine:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget -qO - https://mobaxterm.mobatek.net/download-home-edition.html | grep -i 'MobaXterm.*Home Edition v' | head -n1 | sed -E 's/.*v([0-9.]+).*/\1/')
      snapcraftctl set-version "$ver"
      ./dl_f2k
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
      - sommelier
    build-packages: [wget]
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"
